Development
ialiev685/goit-markup-hw-07 pull request #1
Opened 2021-02-06 21:17 UTC by ialiev685

ДЗ № 7 выполнил. Прошу проверить.

2021-02-07 11:38 UTC, magom001 requested changes
Я тебя призвал в чате. У тебя нет понимания, как нужно организовать код. Ты путаешь layout и components.

2021-02-07 11:38 UTC, magom001 commented on css/style.css
>    --color-darkgray: #2f303a;
зачем нужен этот файл?

2021-02-07 11:38 UTC, magom001 commented on sass/components/_default_options.scss
> +body {
почему ты решил, что это должно лежать в components?

2021-02-12 07:43 UTC, magom001 reviewed
layot -> layout

Лучше, но есть над чем подумать.

2021-02-12 07:43 UTC, magom001 commented on sass/components/_button.scss
> +    margin-left: auto;
В компоненте не должно быть margin. Позиционировать кнопку - это обязанность layout

2021-02-12 07:43 UTC, magom001 commented on sass/components/_button.scss
> +  &--send {
Ты опять недопонимаешь компонентный подход. Почему send? А если будет синяя кнопка 'call'?

Кнопка живет вне контекста. Она есть кнопка. Ей пофиг, что она делает. У тебя может быть просто серая кнопка (.button). Может быть синяя кнопка (.button--primary или --blue, или еще как-то). Лучше --primary, потому что --blue тебя обяжет делать ее синей.

2021-02-12 07:43 UTC, magom001 commented on sass/components/_button.scss
> +    cursor: pointer;
вот это общее свойство для ВСЕХ кнопок

2021-02-12 07:43 UTC, magom001 commented on sass/components/_footer.scss
> +.button {
неправильно

 у тебя не должно быть глобального селектора .button. Если это кнопки внутри футера, то так и пиши:

.footer {
    &__button-social-network {
        ....
    }
}

Вообще кажется, что components/_footer не место быть. Достаточно в layout разложить компоненты по своим местам. Тем более что ниже ты создаешь layout footer

2021-02-12 07:43 UTC, magom001 commented on sass/components/_footer.scss
> +.footer-form {
....&__form {}

2021-02-12 07:43 UTC, magom001 commented on sass/components/_header.scss
> +.site-nav {
вот это все должно жить внутри .header,  если ты пишешь это в файле components/_header, или это должно лежать где-то отдельно.

2021-02-12 07:43 UTC, magom001 commented on sass/components/_input.scss
> +.input {
Что-то тут очень мало стилей. Подозреваю, что ты это где-то ниже размазал.

Не вижу тут ничего про hover,  не вижу ничего про иконку как на форме

2021-02-12 07:43 UTC, magom001 commented on sass/components/_modal_window.scss
> +  &__field-checkbox {
это прям кандидат на вынос в компоненту

2021-02-12 07:43 UTC, magom001 commented on sass/components/_header.scss
> +  &__link {
кандидат на компоненту

2021-02-12 20:13 UTC, ialiev685 commented on sass/components/_button.scss
> +  &--send {
done

2021-02-12 20:22 UTC, ialiev685 commented on sass/components/_button.scss
> +    cursor: pointer;
done

2021-02-12 21:11 UTC, ialiev685 commented on sass/components/_footer.scss
> +.button {
done

2021-02-12 21:12 UTC, ialiev685 commented on sass/components/_footer.scss
> +.footer-form {
done

2021-02-12 21:34 UTC, ialiev685 commented on sass/components/_input.scss
> +.input {
hover в инпут по проекту отсутствует.

2021-02-12 21:57 UTC, ialiev685 commented on sass/components/_input.scss
> +.input {
done

2021-02-12 22:12 UTC, ialiev685 commented on sass/components/_modal_window.scss
> +  &__field-checkbox {
done

2021-02-12 22:13 UTC, ialiev685 commented on sass/components/_button.scss
> +    margin-left: auto;
done

2021-02-12 22:36 UTC, ialiev685 commented on sass/components/_header.scss
> +  &__link {
done

2021-02-12 22:36 UTC, ialiev685 commented on sass/components/_header.scss
> +.site-nav {
done

2021-02-15 06:53 UTC, magom001 approved these changes
неплохо

2021-02-15 15:00 UTC, merged